# Generated by Django 4.0.1 on 2022-12-29 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='tabledb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sno', models.IntegerField()),
                ('l2id', models.CharField(max_length=10)),
                ('task', models.CharField(max_length=100)),
                ('start', models.DateField()),
                ('finish', models.DateField()),
            ],
        ),
    ]
