# Generated by Django 4.0.1 on 2022-12-30 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tabledb',
            name='finish',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='tabledb',
            name='start',
            field=models.CharField(max_length=10),
        ),
    ]
